### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by seriaati** [azuse/youtube-streaming-translator-python#3]
What do these errors mean, which part did I did it wrong?
![image](https://user-images.githubusercontent.com/61446626/103721539-dba64700-5008-11eb-877f-5e5352c648bb.png)

**Comment by seriaati** [comment]
I tried to reinstall and found this error when doing pip install -r requirements.txt
![image](https://user-images.githubusercontent.com/61446626/103722376-c500ef80-500a-11eb-82b7-ef625d954990.png)

**Comment by azuse** [comment]
> What do these errors mean, which part did I did it wrong?
> ![image](https://user-images.githubusercontent.com/61446626/103721539-dba64700-5008-11eb-877f-5e5352c648bb.png)

In this case, try to run  
```
pip install requests
pip install pafy
pip install m3u8
```
to directly install the package required.



> I tried to reinstall and found this error when doing pip install -r requirements.txt
> ![image](https://user-images.githubusercontent.com/61446626/103722376-c500ef80-500a-11eb-82b7-ef625d954990.png)

requirements.txt is a list of packages that scripts required, it seems that some package failed to install but the screenshot can't tell which. You can try to locate which package it is and search how to install it.
