### ISSUE TITLE
老哥求助

### ISSUE THREAD

**Issue by baco997** [azuse/youtube-streaming-translator-python#6]
![Snipaste_2021-12-11_21-17-59](https://user-images.githubusercontent.com/44056459/145678066-4f3f935c-689f-49a2-b439-f4fdbc0be524.png)
这种报错怎么解决呀

**Comment by azuse** [comment]
应该是youtube隐藏了dislike数值导致的，更新下pafy，或者找这个报错的位置，把self._dislike改成=0

**Comment by baco997** [comment]
成功了兄弟，感谢
